project_id = "yazmxlgfraauuhmsnysh"

[functions.generate-html]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.update-payment-method]
verify_jwt = true

[functions.change-plan]
verify_jwt = true